<?php
/**
 * @file
 * Provides a Views plugin for displaying images in a Mosaic Grid layout.
 */

/**
 * Implements hook_autoload_info().
 */
function mosaic_grid_autoload_info() {
  return array(
    'views_plugin_style_mosaic_grid' => 'views_plugin_style_mosaic_grid.inc',
  );
}

/**
 * Load include file.
 */
module_load_include('inc', 'mosaic_grid', 'mosaic_grid.views');

/**
 * Implements hook_views_api().
 */
function mosaic_grid_views_api() {
  return array(
    'api' => '3.0',
    'path' => backdrop_get_path('module', 'mosaic_grid'),
    'template_path' => backdrop_get_path('module', 'mosaic_grid'),
  );
}

/**
 * Implements hook_library_info().
 */
function mosaic_grid_library_info() {
  $libraries['flexImages'] = array(
    'title' => 'Flex Images',
    'website' => 'https://goodies.pixabay.com/jquery/flex-images/demo.html',
    'version' => '1.0.4',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.min.js' => array(
        'weight' => 1,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.flex-images.css' => array(),
    ),
  );

  $libraries['lazyloadxt'] = array(
    'title' => 'Lazy Load XT',
    'website' => 'http://ressio.github.io/lazy-load-xt/',
    'version' => '1.1.0',
    'js' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.min.js' => array(
        'weight' => 2,
      ),
    ),
    'css' => array(
      backdrop_get_path('module', 'mosaic_grid') . '/library/jquery.lazyloadxt.fadein.min.css' => array(),
    ),
  );
  return $libraries;
}

/**
 * Implements hook_menu().
 */
function mosaic_grid_menu() {
  $items['admin/config/media/mosaic_grid'] = array(
    'title' => 'Mosaic Grid',
    'description' => 'Configure global options for Mosaic Grid views formatter.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('mosaic_grid_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'mosaic_grid.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_config_info().
 */
function mosaic_grid_config_info() {
  return array(
    'mosaic_grid.settings' => array(
      'label' => t('Mosaic Grid settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_theme().
 * Registers theme function that renders a single item(image with a caption)
 * of the Mosaic Grid. Check mosaic_grid_item.theme.inc for variables
 * explanation.
 */
function mosaic_grid_theme($existing, $type, $theme, $path) {
  return array(
    'mosaic_grid_item' => array(
      'variables' => array(
        'image_rendered'  => '',
        'width'           => 0,
        'height'          => 0,
        'text_rendered'   => '',
        'options' => array(
          'gap' => 0,
          'captions' => array(
            'display' => 'static',
            'source'  => '',
          ),
        ),
      ),
      'file' => 'mosaic_grid_item.theme.inc',
    ),
  );
}

/**
 * Implements hook_views_pre_build().
 * Forces some multiple value fields setting.
 * It is crucial to have multiple display type to be
 * a list so that theme_item_list hook is envoked.
 * Otherwise Mosaic Grid will render incorrectly.
 */
function mosaic_grid_views_pre_build(&$view) {
  // Get current display.
  $display = $view->display[$view->current_display];
  // Make sure it uses Mosaic Grid style pplugin.
  if (!empty($display->display_options['style_plugin'])
      && $display->display_options['style_plugin'] == 'mosaic_grid') {
    // Loop through field with multiple values.
    foreach ($view->field as $field) {
      if (!empty($field->multiple)) {
        // With grouping off it still works but makes no practical sence.
        $field->options['group_rows'] = TRUE;
        // Force list display type. Important!
        if ($field->options['multi_type'] == 'separator') {
          $field->options['multi_type'] = 'ul';
        }
      }
    }
  }
}

/**
 * Implements hook_views_pre_render().
 * Displays warning about styles in preview mode.
 */
function mosaic_grid_views_pre_render(&$view) {
  if (isset($view->preview)) {
    $options = $view->style_plugin->options;
    if (!empty($options['captions']['source'])) {
      // Get deafault and views theme names.
      $default_theme_name = config_get('system.core', 'theme_default');
      $views_theme_name = config_get('views_ui.settings', 'custom_theme');
      if (!$views_theme_name || $views_theme_name == '_default')
        $views_theme_name = config_get('system.core', 'admin_theme');
      // Show warning if views and default themes are not the same.
      if ($views_theme_name != $default_theme_name) {
        $themes = list_themes();
        $views_human_name = $themes[$views_theme_name]->info['name'];
        $default_human_name = $themes[$default_theme_name]->info['name'];
        backdrop_set_message(
          t("This preview uses styles from theme %admin. Make sure to check the final look of captions with your site's default theme (%default).", array('%admin' => $views_human_name, '%default' => $default_human_name)),
          'warning'
        );
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Makes adjustment to Multiple field settings form to show user
 * that some of the parameters are overriden by the Mosaic Grid.
 */
function mosaic_grid_form_views_ui_config_item_form_alter(&$form, &$form_state, $form_id) {
  // Get style plugin.
  if (!empty($form_state['view']->display_handler)) {
    $style_plugin = $form_state['view']->display_handler->get_plugin('style');
  }
  // Check if Mosaic Grid is used as style.
  if (empty($style_plugin->plugin_name) || $style_plugin->plugin_name != 'mosaic_grid') {
    return;
  }
  // If this is a multiple field form, apply changes.
  if (!empty($form['options']['multiple_field_settings'])) {
    // Remove options that are overriden by the Mosaic Grid.
    unset($form['options']['group_rows']);
    unset($form['options']['multi_type']['#options']['separator']);
    unset($form['options']['separator']);
    // Show fields that can be hidden(when value grouping is off)
    // but are still relevant to the Mosaic Grid plugin.
    unset($form['options']['multi_type']['#states']['visible']);
    unset($form['options']['delta_limit']['#states']['visible']);
    unset($form['options']['delta_offset']['#states']['visible']);
    unset($form['options']['delta_reversed']['#states']['visible']);
    unset($form['options']['delta_first_last']['#states']['visible']);
    // Add notice that settings have been mingled with.
    $form['options']['multiple_field_settings']['mosaic_grid_notice'] = array(
      '#prefix' => '<div class="messages info">',
      '#markup' => t('%multiple are partially overriden by the %mosaic style plugin set for this display.',
        array(
          '%multiple' => $form['options']['multiple_field_settings']['#title'],
          '%mosaic'   => $style_plugin->plugin_title(),
      )),
      '#suffix' => '</div>',
    );
  }
}

/**
 * Preprocess function for module's template views_view_mosaic-grid.tpl.php.
 * Renders Mosaic Grid items, loads libraries and generates styles according
 * to the plugin options.
 */
function template_preprocess_views_view_mosaic_grid(&$vars) {
  // Get current view.
  $view = $vars['view'];
  // Get style plugin for this view.
  $style_plugin = $view->style_plugin;
  // Get config and plugin options.
  $config  = config('mosaic_grid.settings');
  $options = $vars['options'];

  // Get available image field handlers.
  $image_fields = $style_plugin->get_all_image_fields();

  // Do nothing if no image fields found.
  if (empty($image_fields)) {
    return;
  }

  // Iterate over the array of rendered fields.
  foreach ($style_plugin->rendered_field_values as $row_index => $row_data) {
    // Iterate over image fields.
    foreach ($image_fields as $image_field) {
      // Get image field id.
      $image_field_id  = $image_field->options['id'];
      // Image raw value is needed for width and height, alt and title texts.
      $image_raw_value = $image_field->get_items($view->result[$row_index]);
      // Check if rendered image field exist in the array of rendered fields.
      if (empty($style_plugin->rendered_field_values[$row_index][$image_field_id])) {
        continue;
      }
      // Get rendered image field. For multi value fields this is array of rendered values
      // that was captured in template_list_items hook.
      $image_rendered = $style_plugin->rendered_field_values[$row_index][$image_field_id];
      if (!is_array($image_rendered)) {
        // For single value fields make it an array with one value so that there
        // is one iteraion process for both multivalue and single value fields.
        $image_rendered = array($image_rendered);
      }
      // Iterate over every value of an image field.
      foreach ($image_rendered as $i => $image_rendered_value) {
        // Get caption text depending on caption text source setting.
        $caption_text = '';
        if (!empty($options['captions']['source'][$image_field_id])) {
          $caption_source = $options['captions']['source'][$image_field_id];
          switch ($caption_source) {
            case 'alt_tag':
              if (!empty($image_raw_value[$i]['rendered']['#item']['alt'])) {
                // The raw value array contains alt tag with rendered tokens.
                $caption_text = $image_raw_value[$i]['rendered']['#item']['alt'];
              }
              break;
            case 'title_tag':
              if (!empty($image_raw_value[$i]['rendered']['#item']['title'])) {
                // The raw value array contains title tag with rendered tokens.
                $caption_text = $image_raw_value[$i]['rendered']['#item']['title'];
              }
              break;
            default:
              // Other caption source values should refer to a text field.
              if (!empty($style_plugin->rendered_field_values[$row_index][$caption_source])) {
                $text_field_rendered = $style_plugin->rendered_field_values[$row_index][$caption_source];
                if (!is_array($text_field_rendered)) {
                  // For single value make it an array with one value. That way if
                  // multi value image field has single value text field as a text source,
                  // then only the first image of all image values gets the caption text.
                  $text_field_rendered = array($text_field_rendered);
                }
                if (!empty($text_field_rendered[$i])) {
                  $caption_text = $text_field_rendered[$i];
                }
              }
          }
        }

        $width  = $image_raw_value[$i]['raw']['width' ];
        $height = $image_raw_value[$i]['raw']['height'];

        // Adjust image dimensions with regard of image style.
        if (!empty($style_plugin->image_styles[$image_field_id])) {
          $dimentions = array('width' => $width, 'height' => $height);
          image_style_transform_dimensions(
            $style_plugin->image_styles[$image_field_id],
            $dimentions
          );
          $width  = (int)$dimentions['width'];
          $height = (int)$dimentions['height'];
        }

        // Render a Mosaic Grid item with an image and a caption text.
        $mosaic_grid_item = theme(
          'mosaic_grid_item',
          array(
              'image_rendered'  => $image_rendered_value,
              'width'           => $width,
              'height'          => $height,
              'text_rendered'   => $caption_text,
              'options'         => $options,
          )
        );
        // Save the item to an array that will be used for gallery generation.
        $style_plugin->rendered_mosaic_items[] = $mosaic_grid_item;
      }
    }
  }

  // Create unique id for the mosaic grid.
  $mosaic_id = 'mosaic-grid-' . $view->name . '-' . $view->current_display;

  // Store data in variables to be easily accessible by the template.
  $vars['rendered_mosaic_items'] = $style_plugin->rendered_mosaic_items;
  $vars['mosaic_id']             = $mosaic_id;
  $vars['lazyload_enabled']      = $config->get('lazyload_enabled');

  // Create settings array for js.
  $js_settings = array(
    'mosaic_grid' => array(
      $mosaic_id => array(
        'max_row_height' => $options['max_row_height'],
        'max_rows'       => $options['max_rows'],
        'truncate'       => $options['truncate'],
      ),
    ),
  );

  // Get module's directory.
  $module_dir = backdrop_get_path('module', 'mosaic_grid');

  // Add flexImages jQuery library.
  backdrop_add_library('mosaic_grid', 'flexImages', FALSE);

  // If lazyload is enabled then do all related setup.
  if ($config->get('lazyload_enabled')) {
    // Add lazyload javascript settings.
    $js_settings['mosaic_grid']['lazyload'] = array(
        'edgeY' => $config->get('lazyload_edgeY'),
      );

    // Add lazyLoadXt library.
    backdrop_add_library('mosaic_grid', 'lazyloadxt', FALSE);

    // Check loader style setting.
    $loader_style = $config->get('loader_style');

    // If one of the loader styles selected then add it's CSS file.
    if (!empty($loader_style)) {
      backdrop_add_css($module_dir . '/css/mosaic_grid_loader_' . $loader_style . '.css');

      // Add color customisation as inline css.
      $color_hex = $config->get('loader_color');
      switch ($loader_style) {
        case 'spinning_ring':
        case 'spinning_ring_thin':
          // Check if color is a valid hex color and convert it to rgb.
          if (Color::validateHex($color_hex)) {
            $color = Color::hexToRgb($color_hex);
          }
          else {
            $color = Color::hexToRgb('#ffffff');
          }
          $loader_custom_css = "
            .mosaic-grid-loader {
              border-color: rgba({$color['red']}, {$color['green']}, {$color['blue']}, 0.2);
              border-left-color: {$color_hex};
            }";
          break;

        case 'floating_balls':
        case 'three_dots':
        case 'square_blocks':
          $loader_custom_css = "
            .mosaic-grid-loader {
              color: {$color_hex};
            }";
          break;

        case 'vertical_blocks':
          $loader_custom_css = "
            .mosaic-grid-loader,
            .mosaic-grid-loader:before,
            .mosaic-grid-loader:after {
              background: {$color_hex};
              color: {$color_hex};
            }";
          break;
      }
    }
  }

  // Add settings and load js to initiate plugins.
  backdrop_add_js($js_settings, 'setting');
  backdrop_add_js($module_dir . '/js/mosaic_grid.js');

  // Load module's styles.
  backdrop_add_css($module_dir . '/css/mosaic_grid.css');

  // The rest of the function code below generates customized CSS, based on
  // configuration, and module options.
  $custom_css = empty($loader_custom_css) ? '' : $loader_custom_css;

  // Set caption height options.
  $height = '';
  switch ($options['captions']['height']['option']) {
    case 'fixed':
      $height .= 'height: ' . $options['captions']['height']['value'] . 'em;';
      // Intentionally no break here. Max-height is needed anyway.
    case 'limit':
      $height .= 'max-height: ' . $options['captions']['height']['value'] . 'em;';
      break;
  }

  // Create style overrides if caption style is set to custom.
  if ($config->get('caption_style_override')) {
    // Get settings for caption style.
    $font_color  = $config->get('caption_font_color');
    $bg_color    = $config->get('caption_background_color');
    $opacity     = $config->get('caption_opacity') / 100;
    $font_size   = $config->get('caption_font_size');
    $padding     = $config->get('caption_padding');
    $padding_h   = $options['captions']['no_padding_h'] ? 0 : $padding * 1.5;

    // Check if background color is a valid hex color and convert it to rgb.
    if (Color::validateHex($bg_color)) {
      $color = Color::hexToRgb($bg_color);
    }
    else {
      $color = Color::hexToRgb('#000000');
    }
    // Create css with inserted values.
    $custom_css .= "
      .mosaic-grid-caption {
        color: {$font_color};
        background: rgba({$color['red']}, {$color['green']}, {$color['blue']}, {$opacity});
        font-size: {$font_size}em;
        {$height}
        padding: {$padding}em {$padding_h}em;
      }
      .mosaic-grid-caption * {
        color: {$font_color} !important;
      }";
  }
  else {
    if ($options['captions']['no_padding_h']) {
      // Make 'no horisontal padding' work even when no custom caption style set.
      $custom_css .= "
        .mosaic-grid-caption {
          padding-left: 0em;
          padding-right: 0em;
        }";
    }
    if ($height != '') {
      $custom_css .= "
        .mosaic-grid-caption {
          {$height}
        }";
    }
  }
  // Minify generated stylesheet and add it to the page.
  if ($custom_css != '') {
    $vars['custom_css'] = backdrop_load_stylesheet_content($custom_css, TRUE);
    backdrop_add_css($vars['custom_css'], array('type' => 'inline'));
  }
}



/**
 * Implements hook_preprocess_item_list().
 * Captures rendered field values and saves them to an array
 * before item_list theme assembles them into 'ul' or 'ol' list.
 */
function mosaic_grid_preprocess_item_list(&$vars) {
  // Check if there is an active view with Mosaic Grid style plugin.
  $view = views_get_current_view();
  if (!isset($view) || !is_object($view)) return;
  $style_plugin = $view->style_plugin;
  if ($style_plugin->plugin_name != 'mosaic_grid') return;

  // Get id of a field that is being rendered.
  if (!isset($style_plugin->field_now_rendered) || !isset($view->row_index)) {
    return;
  }
  $field_id = $style_plugin->field_now_rendered;

  // Save field values(items). Before item_list renders them
  // into a list, they are packed in array and this what we need.
  $style_plugin->rendered_field_values[$view->row_index][$field_id] = $vars['items'];
}

/**
 * Implements hook_preprocess_image().
 * Prepares images for lazy loading script.
 */
function mosaic_grid_preprocess_image(&$variables) {
  // Check if there is an active view with Mosaic Grid style plugin.
  $view = views_get_current_view();
  if (!isset($view) || !is_object($view)) return;
  if ($view->style_plugin->plugin_name != 'mosaic_grid') return;

  // Check if image lazy loading is enabled in module settings.
  $lazyload = config_get('mosaic_grid.settings', 'lazyload_enabled');
  if (!$lazyload) return;

  // Change src attribute to blank image and assign actual image url to lazy-src.
  // This is required for lazy loading js plugin to work.
  $path_or_uri = $variables['uri'] ? $variables['uri'] : $variables['path'];
  $variables['attributes']['lazy-src'] = file_create_url($path_or_uri);
  $variables['attributes']['src'] = "data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==";
}

