<?php

/**
 * Implements hook_fontyourface_info().
 */
function google_fonts_api_fontyourface_info() {

  $info = array(
    'name' => 'Google',
    'url' => 'https://code.google.com/webfonts',
    'base_path' => 'https://www.google.com/webfonts/family?family=',
  );

  return $info;

}

/**
 * Implements hook_fontyourface_preview().
 */
function google_fonts_api_fontyourface_preview($font, $text = NULL, $size = 18) {

  $output = '';

  if ($text == NULL) {
    $text = $font->name;
  }

  if ($size == 'all') {

    // Display variety of sizes.

    $sizes = array(32, 24, 18, 14, 12, 10);

    foreach ($sizes as $size) {

      $output .= '<div style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</div>';

    }

  }
  else {

    // Display single size.

    $output = '<span style="' . fontyourface_font_css($font) . ' font-size: ' . $size . 'px; line-height: ' . $size . 'px;">' . $text . '</span>';

  }

  return $output;

}

/**
 * Implements template_preprocess_page().
 */
function google_fonts_api_preprocess_page(&$vars) {
  if (!empty($vars['fontyourface'])) {

    $paths = array();
    $subsets = array();

    foreach ($vars['fontyourface'] as $used_font) {

      if ($used_font->provider == 'google_fonts_api') {

        $metadata = unserialize($used_font->metadata);

        $path_parts = explode(':', $metadata['path']);

        $subsets[$path_parts[0]][$metadata['subset']] = $metadata['subset'];
        $all_subsets[$metadata['subset']] = $metadata['subset'];

        if (!isset($paths[$path_parts[0]])) {
          $paths[$path_parts[0]] = array();
        }

        if (count($path_parts) > 1) {
          $paths[$path_parts[0]][$path_parts[1]] = $path_parts[1];
        }
        else {
          $paths[$path_parts[0]]['regular'] = 'regular';
        }

      }

    }

    if (count($paths) > 0) {

      $families = array();

      foreach ($paths as $family => $variants) {
        $families[$family] = urlencode($family) . ':' . implode(',', $variants);
      }

      if (module_exists('google_webfont_loader_api')) {

        foreach ($families as $family => $family_with_variants) {

          $font_info = array(
            'name' => 'Google ' . $family,
            'google_families' => array($family_with_variants . ':' . implode(',', $subsets[$family])),
          );

          _google_webfont_loader_api_load_font($font_info);

        }

      }
      else {

        $base = 'https://fonts.googleapis.com/css?family=';

        if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') {
          $base = 'https://fonts.googleapis.com/css?family=';
        }

        $url = $base . implode('|', $families) . '&subset=' . implode(',', $all_subsets);

        fontyourface_add_css_in_preprocess($vars, $url, 'remote');

      }

    }

  }

}

/**
 * Implements hook_fontyourface_import().
 */
function google_fonts_api_fontyourface_import() {

  // Return the JSON object with all available fonts

  $fonts = array();
  $json_font_list = _google_fonts_api_get_fonts_from_api();
  if (!$json_font_list) {
    return FALSE;
  }
  $fonts = _google_fonts_api_convert_api_results($json_font_list);

  fontyourface_log('google_fonts_api_fontyourface_import fonts: @fonts', array('@fonts' => print_r($fonts, TRUE)));

  foreach ($fonts as $font) {

    if (!isset($font->tags)) {
      $font->tags = array();
    }
    fontyourface_save_font($font);

  }

  return TRUE;
}

/**
 * Retrieves fonts from api and parses them for consumption.
 *
 * @param string $key
 *   An API key to use for testing.
 *
 * @return array|false
 *   List of fonts or FALSE.
 */
function _google_fonts_api_get_fonts_from_api($key = '') {
  // Return the JSON object with all available fonts.
  $google_api_key = $key ?: config_get('fontyourface.settings', 'google_fonts_api_key');

  // This key is limited to 10000 requests per day, which should
  // be sufficient as it is only used when selecting fonts in the
  // admin interface. After that, the fonts are cached in Backdrop.

  try {
    $uri = 'https://www.googleapis.com/webfonts/v1/webfonts?key=' . $google_api_key;
    $response = backdrop_http_request($uri);
    fontyourface_log('backdrop_http_request response: @response', array('@response' => print_r($response, TRUE)));
    if ($response->code == 200) {
      $json_results = json_decode($response->data);
      return $json_results->items;
    }
    else {
      // Connection was successful but Google responded with an error code.
      throw new \Exception();
    }
  }
  catch (Exception $e) {
    backdrop_set_message(t('The list of Google Fonts could not be fetched. Verify that your server can connect the Google Servers (https://www.googleapis.com). Error: %error', array('%error' => $response->error)), 'error');

    return FALSE;
  }
}

/**
 * Implements hook_views_api().
 */
function google_fonts_api_views_api() {

  if (module_exists('fontyourface_ui')) {

    return array(
      'api' => 2,
      'path' => backdrop_get_path('module', 'google_fonts_api') . '/views',
    );

  }

}

/**
 * Converts the Google Fonts API JSON results to a generic Fonts object array
 *
 * @param array $json_font_list
 *   Array of Font objects.
 *
 * @return array
 */
function _google_fonts_api_convert_api_results($json_font_list) {
  $fonts = array();
  foreach ($json_font_list as $json_font) {
    foreach ($json_font->variants as $json_font_variant) {
      foreach ($json_font->subsets as $json_font_subset) {

        $font_id = $json_font->family . ' ' . $json_font_variant . ' (' . $json_font_subset . ')';

        switch ($json_font_variant) {
          case 'regular':
            $css_style = 'normal';
            $css_weight = 'normal';
            break;

          case 'italic':
            $css_style = 'italic';
            $css_weight = 'normal';
            break;

          case 'bold':
            $css_style = 'normal';
            $css_weight = 'bold';
            break;

          case 'bolditalic':
            $css_style = 'italic';
            $css_weight = 'bold';
            break;

          default:
            // For all other cases (eg 400 or 400italic)
            if (is_numeric($json_font_variant)) {
              // Variant is a number, like 400
              $css_style = 'normal';
              $css_weight = $json_font_variant;
            }
            elseif (is_numeric(substr($json_font_variant, 0, 3))){
              // Variant is a combined string of number and string, like 400italic
              // The numberic part is always three characters long, so we can split it easily
              $css_style = substr($json_font_variant, 3);
              $css_weight = substr($json_font_variant, 0, 3);
            }
        }

        $fonts[$font_id] = new stdClass;
        $fonts[$font_id]->name = $font_id;
        $fonts[$font_id]->url = 'https://www.google.com/webfonts/family?family=' . $json_font->family . '&subset=' . $json_font_subset . '#' . $json_font_variant;
        $fonts[$font_id]->provider = 'google_fonts_api';
        $fonts[$font_id]->css_family = $json_font->family;
        $fonts[$font_id]->css_style = $css_style;
        $fonts[$font_id]->css_weight = $css_weight;
        $fonts[$font_id]->foundry = '';
        $fonts[$font_id]->foundry_url = '';
        $fonts[$font_id]->license = '';
        $fonts[$font_id]->license_url = '';
        $fonts[$font_id]->metadata = serialize(array('path' => $json_font->family . ':' . $json_font_variant, 'subset' => $json_font_subset));

        $tag_object = new StdClass;
        $tag_object->type = 'subset';
        $tag_object->name = $json_font_subset;
        $fonts[$font_id]->tags[] = $tag_object;

      }
    }
  }

  return $fonts;

}


/**
 * Implements hook_form_FORM_ID_alter().
 */
function google_fonts_api_form_fontyourface_ui_settings_form_alter(&$form, &$form_state) {
  $form['google_fonts_api'] = array(
    '#type' => 'fieldset',
    '#title' => t('Google Fonts'),
    '#weight' => -1,
    'google_fonts_api_key' => array(
      '#type' => 'textfield',
      '#title' => t('Google API Key'),
      '#description' => t('Add your Google API key to import fonts. Available at ') . l('developers.google.com/fonts/docs/developer_api#APIKey', 'https://developers.google.com/fonts/docs/developer_api#APIKey'),
      '#default_value' => config_get('fontyourface.settings', 'google_fonts_api_key'),
    ),
    'google_api_save' => array(
      '#type' => 'submit',
      '#value' => t('Save Google API key'),
    ),
  );
  // Move the default update/import button to the Google Fonts fieldset
    if (isset($form['providers']['google_fonts_api_import'])) {
      $form['google_fonts_api']['google_fonts_api_import'] = $form['providers']['google_fonts_api_import'];
      unset($form['providers']['google_fonts_api_import']);
    }
  $form['google_fonts_api']['google_fonts_api_import']['#disabled'] = !(bool) config_get('fontyourface.settings', 'google_fonts_api_key');

  $form['#validate'][] = 'google_fonts_api_form_fontyourface_ui_settings_form_validate';
  $form['#submit'][] = 'google_fonts_api_form_fontyourface_ui_settings_form_submit';

}

/**
 * Form validation handler for Google Font settings.
 */
function google_fonts_api_form_fontyourface_ui_settings_form_validate(&$form, &$form_state) {
  if ($form_state['clicked_button']['#parents'][0] != 'google_api_save') {
    return;
  }
  $google_fonts_api_key = trim($form_state['values']['google_fonts_api_key']);
  if ($google_fonts_api_key) {
    $connection_works = _google_fonts_api_get_fonts_from_api($google_fonts_api_key);
    if (!$connection_works) {
      form_set_error('google_fonts_api_key', t('The API Key is invalid.'));
    }
  }
  else {
    form_set_error('google_fonts_api_key', t('The API Key is required.'));
  }
}

/**
 * Form submit handler for Google Font settings.
 */
function google_fonts_api_form_fontyourface_ui_settings_form_submit(&$form, &$form_state) {
  if ($form_state['clicked_button']['#parents'][0] != 'google_api_save') {
    return;
  }
  $values = $form_state['values'];
  config_set('fontyourface.settings', 'google_fonts_api_key', $values['google_fonts_api_key']);
  backdrop_set_message(t('API key successfully saved.'));
}
